### ISSUE TITLE
i just login to my account and my etc not there 

### ISSUE THREAD

**Issue by alexprorbp** [ethereumproject/etherwallet#52]
hi i just login to my account and my ETC is not there keep saying loading where is my etc ???

**Comment by alexprorbp** [comment]
this is my address why is loading ?0x4672fFA6A027BEe95C1a9F6a45A1B5EF0Cc3671b

**Comment by splix** [comment]
@alexprorbp https://www.reddit.com/r/EthereumClassic/comments/6kcwmi/attention_classicetherwalletcom_has_been_hijacked/

**Comment by splix** [comment]
please don't use the wallet until issue will be resolved

**Comment by alexprorbp** [comment]
i jus check my wallet on other website my etc gone why ? will i get it back?

**Comment by alexprorbp** [comment]
pupec

**Comment by splix** [comment]
http://gastracker.io/addr/0x4672fFA6A027BEe95C1a9F6a45A1B5EF0Cc3671b has 13.7899 ether at the moment, I don't see any outcoming transactions.

Please don't enter your password to private key at other websites

**Comment by splix** [comment]
You can also move your coins to another place, by using https://myetherwallet.com/

**Comment by alexprorbp** [comment]
i don't see no etc no were ! its gone can u send it out to this address for me 0x2504c2278bd8ca401cc9e72140d67ab10436c750

**Comment by alexprorbp** [comment]
please i just change my miners to other wallet to this one can u send my etc there please i don't see no etc in my wallet i just checked it is 13.7 but i don't see them please send it to my wallet on market 0x2504c2278bd8ca401cc9e72140d67ab10436c750

**Comment by alexprorbp** [comment]
i was trying to move how u say but its say 0 balance

**Comment by splix** [comment]
http://gastracker.io/addr/0x4672fFA6A027BEe95C1a9F6a45A1B5EF0Cc3671b says that all coins are still there. what do you use to check balance?

**Comment by splix** [comment]
did you chose ETC in myetherwall? right top corner

**Comment by alexprorbp** [comment]
i just login with my private key

**Comment by alexprorbp** [comment]
no

**Comment by splix** [comment]
ok, switch to "_ETC (epool.io)_" and you'll see your ETC. it shows ETH by default

**Comment by alexprorbp** [comment]
nice  i think i sent them out to market

**Comment by alexprorbp** [comment]
thanks brother

**Comment by kisser228** [comment]
Hey Igor,

Where is my ETC???? Here's the transaction. ALL OF MY $24,000 is GONE! It went to this address:

0x2b8cc0d2901a04145c86c7ae22ca649f974f0e34
 
Transaction Details

Timestamp
Fri Jun 30 01:56:31 UTC 2017
Value
1327.9796 ether
 
1327979559000000000000 Wei
 
$23,624.76
 
 
Hash
0xb8d3b6ee453b0d4841b53532e69677da0868b17474ee237abdf10d4c06e684ad
NOnce
0
From
0x4c6c1e80e06550e7b5f58e19c012ec8a09dd67c5
To
0x2b8cc0d2901a04145c86c7ae22ca649f974f0e34
 
 
Block Height
4004410
Block Hash
0xca586dd3b6c9ed0d684919ad301307f98a87cc81dffdfb7a3336fe323bde3c6c
Gas Provided
21000
Gas Used
21000
Gas Price
21000 Mwei

**Comment by illuminat13** [comment]
0x2be9f2a2dcdc3be51f295fa37e0e568deffbfdb6 - my wallet.
Hi. My ETC  disappeared and were transferred to this address 0x4f0f13a329310749f2820896952def50f0bd295a

**Comment by medolino2009** [comment]
hi, my ether classic also stolen : http://gastracker.io/addr/0x1174C30E1B14842F482666d7AaD3d9E476B69215

Block: 4002608
Confirmations: 6975
29 Jun 2017, 06:55
From my adres: 0x1174c30e1b14842f482666d7aad3d9e476b69215
TX Hash: 0xbcd93931
43.0866 ether
all gone to this adres: 0xce52bfaf3f4900fecfbf43b8da2890cf59cab323

Is there any way to get it back ? i don't get it... is it really so unsafe this ether classic ???????????
Everything my machines did for one month is gone.... i really hope someone can get it back for me...

Please send it to this adres if possible: 0xa931c2ebcbc6dde30ad93efc57c639e67871c6d4

total : 43.0866 ether
 
I really hope to get it again.... 43 ether is maybe not much for someone but it is very much for me...

Thanx in advance

best regards

Miki
